image: python:latest

test:
  stage: test
  script:
  - pip install -r test/requirements.txt
  - pytest
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs/source/ public
  artifacts:
    paths:
    - public
  only:
  - main
