image: python:latest

pytest:
  stage: test
  script:
  - pip install -r test/requirements.txt
  - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
  - branches
  except:
  - main

mutmut_test:
  stage: test
  script:
  - pip install -r test/requirements.txt
  - mutmut run
  - touch report.xml
  - mutmut junitxml > mutmut.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs/source/ public
  artifacts:
    paths:
    - public
  only:
  - main
