image: python:latest

pytest:
  stage: test
  script:
  - pip install -r test/requirements.txt
  - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-apidoc -o docs/source/ src/market-regression/
  - sphinx-build -b html docs/source/ public
  artifacts:
    paths:
    - public

