image: python:latest

train:
  stage: build
  before_script:
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    - apt-get install git-lfs
    - 'command -v ssh-agent > /dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git remote set-url origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git lfs install
    - pip install -r src/requirements.txt
    - python src/market-regression/train.py data/train.csv model/model.json > model/train.log
    - |     
      CHANGES=$(git status --porcelain | wc -l)
      if [[ "${CHANGES}" -gt 0 ]]; then
        echo "Committing updated files to git"
        git add test/
        git add model/
        git commit -m "Uploaded new logs and model"
        git push -o ci.skip origin HEAD:$CI_COMMIT_BRANCH
      else
        echo "Nothing to commit"
      fi
  only:
  - branches
  except:
  - main
  
pytest:
  stage: test
  script:
  - pip install -r test/requirements.txt
  - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install -r src/requirements.txt
  - sphinx-apidoc -o docs/source/ src/market-regression/
  - sphinx-apidoc -o docs/source/ service/
  - sphinx-build -b html docs/source/ public
  artifacts:
    paths:
    - public
  only:
  - main
  - develop

