image: python:latest

train:
  stage: build
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add "$SSH_PRIVATE_KEY"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - mkdir -p ~/.ssh
    - cat gitlab-known-hosts >> ~/.ssh/known_hosts
  script:
  - pip install -r src/requirements.txt
  - python src/market-regression/train.py data/train.csv test/ > test/log.txt
  - git add test/log.txt
  - git push origin HEAD:$CI_COMMIT_BRANCH
  only:
  - branches
  except:
  - main
  
pytest:
  stage: test
  script:
  - pip install -r test/requirements.txt
  - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install -r src/requirements.txt
  - sphinx-apidoc -o docs/source/ src/market-regression/
  - sphinx-build -b html docs/source/ public
  artifacts:
    paths:
    - public
  only:
  - main
  - develop

